CREATE TABLE `clientes` (
`codigo` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
`nome` VARCHAR(80) NOT NULL,
`nascimento` DECIMAL(8,2) NOT NULL,
`cpf` MEDIUMINT NOT NULL,
`email` VARCHAR(80) NOT NULL,
`fone` MEDIUMINT NOT NULL,
PRIMARY KEY (`codigo`))
ENGINE = InnoDB